name: Java CI with Docker

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t my-java-app .

      - name: Run Tests in Docker container
        run: docker run --rm my-java-app mvn test --file pom.xml

    # Optionally, push Docker image to Docker Hub or another registry
    # - name: Push Docker image
    #   run: |
    #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #     docker tag my-java-app ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
